//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18052
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAutoTS.Properties
{
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double SELL_MIN_RATE {
            get {
                return ((double)(this["SELL_MIN_RATE"]));
            }
            set {
                this["SELL_MIN_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double SELL_MAX_RATE {
            get {
                return ((double)(this["SELL_MAX_RATE"]));
            }
            set {
                this["SELL_MAX_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("demo.etrade.co.kr")]
        public string LOGIN_SERVER {
            get {
                return ((string)(this["LOGIN_SERVER"]));
            }
            set {
                this["LOGIN_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOGIN_ID {
            get {
                return ((string)(this["LOGIN_ID"]));
            }
            set {
                this["LOGIN_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOGIN_PW {
            get {
                return ((string)(this["LOGIN_PW"]));
            }
            set {
                this["LOGIN_PW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOGIN_PUBLIC_PW {
            get {
                return ((string)(this["LOGIN_PUBLIC_PW"]));
            }
            set {
                this["LOGIN_PUBLIC_PW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOGIN_ACCOUNT_PW {
            get {
                return ((string)(this["LOGIN_ACCOUNT_PW"]));
            }
            set {
                this["LOGIN_ACCOUNT_PW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOGIN_AUTO_YN {
            get {
                return ((bool)(this["LOGIN_AUTO_YN"]));
            }
            set {
                this["LOGIN_AUTO_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int BUY_COUNT {
            get {
                return ((int)(this["BUY_COUNT"]));
            }
            set {
                this["BUY_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCOUNT_JSON {
            get {
                return ((string)(this["ACCOUNT_JSON"]));
            }
            set {
                this["ACCOUNT_JSON"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REBUY_JSON
        {
            get
            {
                return ((string)(this["REBUY_JSON"]));
            }
            set
            {
                this["REBUY_JSON"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SELL_OPEN_YN {
            get {
                return ((bool)(this["SELL_OPEN_YN"]));
            }
            set {
                this["SELL_OPEN_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOGIN_TRAY_YN {
            get {
                return ((bool)(this["LOGIN_TRAY_YN"]));
            }
            set {
                this["LOGIN_TRAY_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20140414")]
        public string LAST_DATE
        {
            get {
                return ((string)(this["LAST_DATE"]));
            }
            set {
                this["LAST_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SELL_MAX_BUFFER {
            get {
                return ((double)(this["SELL_MAX_BUFFER"]));
            }
            set {
                this["SELL_MAX_BUFFER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SELL_OPEN_BUFFER {
            get {
                return ((double)(this["SELL_OPEN_BUFFER"]));
            }
            set {
                this["SELL_OPEN_BUFFER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SELL_UPLMT_YN {
            get {
                return ((bool)(this["SELL_UPLMT_YN"]));
            }
            set {
                this["SELL_UPLMT_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double SELL_UPLMT_BUFFER {
            get {
                return ((double)(this["SELL_UPLMT_BUFFER"]));
            }
            set {
                this["SELL_UPLMT_BUFFER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string T1833_FILES {
            get {
                return ((string)(this["T1833_FILES"]));
            }
            set {
                this["T1833_FILES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SELL_MIN_YN {
            get {
                return ((bool)(this["SELL_MIN_YN"]));
            }
            set {
                this["SELL_MIN_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SELL_MAX_YN {
            get {
                return ((bool)(this["SELL_MAX_YN"]));
            }
            set {
                this["SELL_MAX_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PROGRAM_API_2_HTS_YN {
            get {
                return ((bool)(this["PROGRAM_API_2_HTS_YN"]));
            }
            set {
                this["PROGRAM_API_2_HTS_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PROGRAM_HTS_2_API_YN {
            get {
                return ((bool)(this["PROGRAM_HTS_2_API_YN"]));
            }
            set {
                this["PROGRAM_HTS_2_API_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PROGRAM_SYNC_TIME_YN {
            get {
                return ((bool)(this["PROGRAM_SYNC_TIME_YN"]));
            }
            set {
                this["PROGRAM_SYNC_TIME_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOGIN_TRADING_YN {
            get {
                return ((bool)(this["LOGIN_TRADING_YN"]));
            }
            set {
                this["LOGIN_TRADING_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JIF_DATE {
            get {
                return ((string)(this["JIF_DATE"]));
            }
            set {
                this["JIF_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JIF_JSTATUS {
            get {
                return ((string)(this["JIF_JSTATUS"]));
            }
            set {
                this["JIF_JSTATUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BUY_ORDER_CANCEL_31_YN {
            get {
                return ((bool)(this["BUY_ORDER_CANCEL_31_YN"]));
            }
            set {
                this["BUY_ORDER_CANCEL_31_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SELL_ORDER_CANCEL_31_YN {
            get {
                return ((bool)(this["SELL_ORDER_CANCEL_31_YN"]));
            }
            set {
                this["SELL_ORDER_CANCEL_31_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BUY_RE_ORDER_YN {
            get {
                return ((bool)(this["BUY_RE_ORDER_YN"]));
            }
            set {
                this["BUY_RE_ORDER_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SELL_RE_ORDER_YN {
            get {
                return ((bool)(this["SELL_RE_ORDER_YN"]));
            }
            set {
                this["SELL_RE_ORDER_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BUY_COUNT_YN {
            get {
                return ((bool)(this["BUY_COUNT_YN"]));
            }
            set {
                this["BUY_COUNT_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUY_COST_YN {
            get {
                return ((bool)(this["BUY_COST_YN"]));
            }
            set {
                this["BUY_COST_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public double BUY_COST {
            get {
                return ((double)(this["BUY_COST"]));
            }
            set {
                this["BUY_COST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUY_REBUY_YN {
            get {
                return ((bool)(this["BUY_REBUY_YN"]));
            }
            set {
                this["BUY_REBUY_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_MAIN_TOP {
            get {
                return ((int)(this["FORM_MAIN_TOP"]));
            }
            set {
                this["FORM_MAIN_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_MAIN_LEFT {
            get {
                return ((int)(this["FORM_MAIN_LEFT"]));
            }
            set {
                this["FORM_MAIN_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_LOG_TOP {
            get {
                return ((int)(this["FORM_LOG_TOP"]));
            }
            set {
                this["FORM_LOG_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_LOG_LEFT {
            get {
                return ((int)(this["FORM_LOG_LEFT"]));
            }
            set {
                this["FORM_LOG_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_SETTING_TOP {
            get {
                return ((int)(this["FORM_SETTING_TOP"]));
            }
            set {
                this["FORM_SETTING_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_SETTING_LEFT {
            get {
                return ((int)(this["FORM_SETTING_LEFT"]));
            }
            set {
                this["FORM_SETTING_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_TRADING_TOP {
            get {
                return ((int)(this["FORM_TRADING_TOP"]));
            }
            set {
                this["FORM_TRADING_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_TRADING_LEFT {
            get {
                return ((int)(this["FORM_TRADING_LEFT"]));
            }
            set {
                this["FORM_TRADING_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_LOG_WIDTH {
            get {
                return ((int)(this["FORM_LOG_WIDTH"]));
            }
            set {
                this["FORM_LOG_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_LOG_HEIGHT {
            get {
                return ((int)(this["FORM_LOG_HEIGHT"]));
            }
            set {
                this["FORM_LOG_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_TRADING_WIDTH {
            get {
                return ((int)(this["FORM_TRADING_WIDTH"]));
            }
            set {
                this["FORM_TRADING_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FORM_TRADING_HEIGHT {
            get {
                return ((int)(this["FORM_TRADING_HEIGHT"]));
            }
            set {
                this["FORM_TRADING_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SELL_FIX_YN {
            get {
                return ((bool)(this["SELL_FIX_YN"]));
            }
            set {
                this["SELL_FIX_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double SELL_FIX_BUFFER {
            get {
                return ((double)(this["SELL_FIX_BUFFER"]));
            }
            set {
                this["SELL_FIX_BUFFER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SELL_TODAY_YN {
            get {
                return ((bool)(this["SELL_TODAY_YN"]));
            }
            set {
                this["SELL_TODAY_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUY_MINU_YN {
            get {
                return ((bool)(this["BUY_MINU_YN"]));
            }
            set {
                this["BUY_MINU_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUY_DUPLICATE_YN {
            get {
                return ((bool)(this["BUY_DUPLICATE_YN"]));
            }
            set {
                this["BUY_DUPLICATE_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BUY_MAX_YN {
            get {
                return ((bool)(this["BUY_MAX_YN"]));
            }
            set {
                this["BUY_MAX_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double BUY_MAX {
            get {
                return ((double)(this["BUY_MAX"]));
            }
            set {
                this["BUY_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BUY_TIME_YN {
            get {
                return ((bool)(this["BUY_TIME_YN"]));
            }
            set {
                this["BUY_TIME_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double BUY_TIME {
            get {
                return ((double)(this["BUY_TIME"]));
            }
            set {
                this["BUY_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JIF_TIME_START_21 {
            get {
                return ((double)(this["JIF_TIME_START_21"]));
            }
            set {
                this["JIF_TIME_START_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SELL_1833_YN {
            get {
                return ((bool)(this["SELL_1833_YN"]));
            }
            set {
                this["SELL_1833_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double SELL_1833_BUFFER {
            get {
                return ((double)(this["SELL_1833_BUFFER"]));
            }
            set {
                this["SELL_1833_BUFFER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SELL_HALF_YN {
            get {
                return ((bool)(this["SELL_HALF_YN"]));
            }
            set {
                this["SELL_HALF_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double SELL_HALF {
            get {
                return ((double)(this["SELL_HALF"]));
            }
            set {
                this["SELL_HALF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string T1833_JSON
        {
            get
            {
                return ((string)(this["T1833_JSON"]));
            }
            set
            {
                this["T1833_JSON"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20140414")]
        public string T1833_DATE
        {
            get
            {
                return ((string)(this["T1833_DATE"]));
            }
            set
            {
                this["T1833_DATE"] = value;
            }
        }
    }
}
